luxonis_depth_ai:
  ros__parameters:
    camera_model: "OAK-D"  # Adjust if using a different Luxonis camera
    fps: 30
    enable_depth: true
    enable_rgb: true
    enable_imu: true
    publish_tf: true
    stereo:
      confidence_threshold: 200
      lr_check: true
      subpixel: true
    rgb:
      resolution: "1080P"
      fps: 30
    frame_id: "camera_link"
